version: '3.7'
services:
  # App service
  irc-api:
    depends_on:
      - redis
    build:
      context: .
      dockerfile: Dockerfile
    image: irc-api-docker
    container_name: irc-api
    restart: always
    tty: true
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    working_dir: /var/www/irc-api
    environment:
      SERVICE_NAME: irc-api
      SERVICE_TAGS: dev
      REDIS_PORT: ${REDIS_PORT}
      REDIS_HOST: ${REDIS_HOST}
      GIPHY_API_KEY: ${GIPHY_API_KEY}
    volumes:
      - ./:/var/www/irc-api
      - /var/www/irc-api/node_modules
    networks:
      - irc-api-network
  # Redis service
  redis:
    image: redis:latest
    container_name: redis
    command: [
        "redis-server",
        "--bind",
        "redis",
        "--port",
        "6379"
    ]
    volumes:
      - red_data:/var/lib/redis
    ports:
      - '${REDIS_PORT}:${REDIS_PORT}'
    networks:
      - irc-api-network

networks:
  irc-api-network:
    driver: bridge
volumes:
  red_data: {}

